name: deploy dist to docdoc

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to build'
        required: true
        default: main

jobs:
  build-and-deploy-dist:
    runs-on: unbuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-log.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: install deps
        run: npm ci

      - name: build dist
        run: npm run build

      - name: delete remoteprevious dist
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_TOKEN }}
          script: |
            if [ -d ~/servers/docdoc/dist ]; then
              echo "Removing previous dist..."
              rm -rf ~/servers/docdoc/dist
            else
              echo "No previous dist found"
            fi
      - name: push dist to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_TOKEN }}
          source: dist/
          target: ~/servers/docdoc
