name: deploy to docdoc

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to build'
        required: true
        default: main

jobs:
  build-and-deploy:
    runs-on: unbuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
